"""empty message

Revision ID: 69debf25851b
Revises: 9e0f4f24ebcc
Create Date: 2023-07-22 19:31:27.619804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69debf25851b'
down_revision = '9e0f4f24ebcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_publish', sa.Boolean(), nullable=True))
        batch_op.drop_column('id_publish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_publish', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_publish')

    # ### end Alembic commands ###
